"""Provision a mower identity, its Zenoh ACL, and its Jetson deployment bundle."""

import argparse
import asyncio
import json
import logging
import os
import subprocess
import uuid
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from sqlalchemy import select
from sqlalchemy.engine import URL
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

import zenoh
from src.config.database import AsyncSessionLocal
from src.config.http_client import close_http_client
from src.config.settings import settings
from src.config.zenoh_client import ZenohAdminClient
from src.models.mower import MowerModel
from src.repositories.create_mower import create_mower
from src.repositories.mower_identity import register_mower_identity
from src.services.step_ca import ComposeStepCaIssuer, StepCaIssuer

BACKEND_ROOT = Path(__file__).resolve().parents[2]
REPOSITORY_ROOT = BACKEND_ROOT.parent
DEFAULT_JETSON_ENV_FILE = REPOSITORY_ROOT / "nvidia_jetson" / ".env"
DEFAULT_JETSON_ROUTER_ENDPOINT = "tls/host.docker.internal:7448"
JETSON_ROOT = REPOSITORY_ROOT / "nvidia_jetson"
SIMULATED_MOWERS_ROOT = JETSON_ROOT / ".sim" / "mowers"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("scripts.provision_mower")


def mower_certificate_common_name(mower_id: uuid.UUID) -> str:
    return f"mower:{mower_id}"


def write_jetson_env(
    env_file: Path,
    *,
    mower_id: uuid.UUID,
    mower_cert_dir: str,
    router_endpoint: str,
    verify_name_on_connect: bool,
    mower_launch: str = "real",
    tpm_state_dir: Path | None = None,
) -> None:
    """Write the non-secret Compose environment for exactly one mower."""
    env_file.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by backend/src/scripts/provision_mower.py.",
        "# Credentials are mounted separately from MOWER_CERT_DIR.",
        f"MOWER_ID={mower_id}",
        f"MOWER_CERT_DIR={mower_cert_dir}",
        f"MOWER_CREDENTIAL_DIR={mower_cert_dir}",
        f"ZENOH_ROUTER_ENDPOINT={router_endpoint}",
        "ZENOH_BOOTSTRAP_ENDPOINT=tls/host.docker.internal:7449",
        f"ZENOH_VERIFY_NAME_ON_CONNECT={'true' if verify_name_on_connect else 'false'}",
        "ZENOH_BOOTSTRAP_VERIFY_NAME_ON_CONNECT="
        f"{'true' if verify_name_on_connect else 'false'}",
        f"MOWER_LAUNCH={mower_launch}",
        "STM32_CAN_INTERFACE=can0",
        "RPLIDAR_DEVICE=/dev/rplidar",
    ]
    if tpm_state_dir is not None:
        lines.extend(("TPM_TRANSPORT=swtpm", f"SWTPM_STATE_DIR={tpm_state_dir}"))
    env_file.write_text("\n".join((*lines, "")))
    os.chmod(env_file, 0o600)


def issue_certificate(
    *,
    mower_id: uuid.UUID,
    output_dir: Path,
    issuer: StepCaIssuer | None = None,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    version_dir = output_dir / "versions" / "initial"
    if version_dir.exists() or (output_dir / "current").exists():
        raise RuntimeError(f"mower credentials already exist in {output_dir}")
    version_dir.mkdir(parents=True)
    private_key = ec.generate_private_key(ec.SECP256R1())
    subject = x509.Name(
        [
            x509.NameAttribute(x509.NameOID.COUNTRY_NAME, "US"),
            x509.NameAttribute(x509.NameOID.ORGANIZATION_NAME, "EmiSamaTechnologies"),
            x509.NameAttribute(
                x509.NameOID.COMMON_NAME, mower_certificate_common_name(mower_id)
            ),
        ]
    )
    csr = (
        x509.CertificateSigningRequestBuilder()
        .subject_name(subject)
        .add_extension(
            x509.ExtendedKeyUsage([x509.oid.ExtendedKeyUsageOID.CLIENT_AUTH]),
            critical=False,
        )
        .sign(private_key, hashes.SHA256())
        .public_bytes(serialization.Encoding.PEM)
        .decode()
    )
    certificate_pem, ca_chain_pem = (issuer or StepCaIssuer()).sign_csr(csr)
    (version_dir / "mower.key").write_bytes(
        private_key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )
    (version_dir / "mower.crt").write_text(certificate_pem)
    (version_dir / "root_ca.pem").write_text(ca_chain_pem)
    os.chmod(version_dir / "mower.key", 0o600)
    os.chmod(version_dir / "mower.crt", 0o644)
    os.chmod(version_dir / "root_ca.pem", 0o644)
    os.symlink("versions/initial", output_dir / "current")


async def provision_mower(
    args: argparse.Namespace, *, session_factory: async_sessionmaker | None = None
) -> uuid.UUID:
    mower_id = args.mower_id or uuid.uuid4()
    certificate_common_name = mower_certificate_common_name(mower_id)
    device_root_public_key = getattr(args, "device_root_public_key", None)
    if device_root_public_key is not None and not device_root_public_key.is_file():
        raise RuntimeError("the mower TPM public key file must exist when provided")

    if session_factory is None:
        session_factory = AsyncSessionLocal
    async with session_factory() as db:
        mower = await create_mower(
            mower_id=mower_id,
            nickname=args.nickname,
            db=db,
        )
        if device_root_public_key is not None:
            await register_mower_identity(
                mower_id,
                device_root_public_key.read_text(),
                db,
            )
    logger.info("Mower record ready: %s", mower.id)

    try:
        if getattr(args, "simulated", False):
            async with session_factory() as db:
                result = await db.execute(select(MowerModel.id).order_by(MowerModel.id))
                mower_ids = [str(value) for value in result.scalars().all()]
            configure_simulated_router_acl(mower_ids)
        else:
            await ZenohAdminClient().configure_mower_device(
                str(mower_id), certificate_common_name
            )
        certificate_options = {}
        if getattr(args, "certificate_issuer", None) is not None:
            certificate_options["issuer"] = args.certificate_issuer
        issue_certificate(
            mower_id=mower_id,
            output_dir=args.output_dir,
            **certificate_options,
        )
        env_options = {}
        if getattr(args, "tpm_state_dir", None) is not None:
            env_options["tpm_state_dir"] = args.tpm_state_dir
        write_jetson_env(
            args.jetson_env_file,
            mower_id=mower_id,
            mower_cert_dir=args.mower_cert_dir,
            router_endpoint=args.router_endpoint,
            verify_name_on_connect=args.verify_name_on_connect,
            mower_launch=getattr(args, "mower_launch", "real"),
            **env_options,
        )
    finally:
        await close_http_client()

    logger.info(
        "Provisioned mower %s with certificate CN %s", mower_id, certificate_common_name
    )
    return mower_id


def configure_simulated_router_acl(mower_ids: list[str]) -> None:
    """Load local mower ACLs at startup; Zenoh 1.9 cannot change them at runtime."""
    config = json.loads(
        str(zenoh.Config.from_file(str(BACKEND_ROOT / "zenoh-router-mtls.json5")))
    )
    acl = config["access_control"]
    for mower_id in sorted(set(mower_ids)):
        rule_id = f"rule_mower_{mower_id}"
        subject_id = f"subject_mower_{mower_id}"
        acl["rules"].append(
            {
                "id": rule_id,
                "permission": "allow",
                "flows": ["ingress", "egress"],
                "messages": [
                    "put",
                    "declare_subscriber",
                    "liveliness_token",
                    "declare_queryable",
                    "query",
                    "reply",
                    "delete",
                ],
                "key_exprs": [f"mower/{mower_id}/**"],
            }
        )
        acl["subjects"].append(
            {"id": subject_id, "cert_common_names": [f"mower:{mower_id}"]}
        )
        acl["policies"].append(
            {
                "id": f"policy_mower_{mower_id}",
                "subjects": [subject_id],
                "rules": [rule_id],
            }
        )
    text = json.dumps(config, indent=2) + "\n"
    zenoh.Config.from_json5(text)
    local_config = BACKEND_ROOT / ".sim" / "zenoh-router-mtls.json5"
    local_config.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    temporary = local_config.with_suffix(".tmp")
    temporary.write_text(text)
    temporary.chmod(0o600)
    temporary.replace(local_config)
    env_file = BACKEND_ROOT / ".env"
    lines = [
        line
        for line in env_file.read_text().splitlines()
        if not line.startswith("ZENOH_MTLS_CONFIG_FILE=")
    ]
    lines.append("ZENOH_MTLS_CONFIG_FILE=.sim/zenoh-router-mtls.json5")
    env_file.write_text("\n".join(lines) + "\n")
    subprocess.run(
        [
            "docker",
            "compose",
            "-f",
            str(BACKEND_ROOT / "local-docker-compose.yml"),
            "up",
            "-d",
            "--force-recreate",
            "--no-deps",
            "zenoh-mtls",
        ],
        check=True,
        env={**os.environ, "ZENOH_MTLS_CONFIG_FILE": ".sim/zenoh-router-mtls.json5"},
    )


async def provision_with_local_database(args: argparse.Namespace) -> uuid.UUID:
    """Use the local Compose PostgreSQL port from the trusted host process."""
    database_url = URL.create(
        "postgresql+asyncpg",
        username=settings.POSTGRES_USER,
        password=settings.POSTGRES_PASSWORD,
        host="127.0.0.1",
        port=int(os.getenv("LOCAL_POSTGRES_PORT") or "15432"),
        database=settings.POSTGRES_DB,
    )
    engine = create_async_engine(database_url)
    try:
        session_factory = async_sessionmaker(engine, expire_on_commit=False)
        return await provision_mower(args, session_factory=session_factory)
    finally:
        await engine.dispose()


def initialize_simulated_mower(args: argparse.Namespace) -> uuid.UUID:
    """Create one local Compose project, then provision and start its mower."""
    mower_id = args.mower_id or uuid.uuid4()
    mower_dir = SIMULATED_MOWERS_ROOT / str(mower_id)
    credential_dir = mower_dir / "credentials"
    tpm_state_dir = mower_dir / "swtpm-state"
    env_file = mower_dir / "mower.env"
    current_credentials = credential_dir / "current"
    if (credential_dir / "versions" / "initial").exists() or (
        current_credentials.exists() or current_credentials.is_symlink()
    ):
        raise RuntimeError(
            f"mower {mower_id} is already provisioned; start its Compose project"
        )
    if not (BACKEND_ROOT / ".env").is_file():
        raise RuntimeError("backend/.env is required for local mower provisioning")

    for directory in (mower_dir, credential_dir, tpm_state_dir):
        directory.mkdir(parents=True, exist_ok=True, mode=0o700)
        directory.chmod(0o700)

    # Compose needs a mower-specific env file before tpm-init can run.
    env_file.write_text(
        f"MOWER_ID={mower_id}\n"
        f"MOWER_CREDENTIAL_DIR={credential_dir}\n"
        f"ZENOH_ROUTER_ENDPOINT={DEFAULT_JETSON_ROUTER_ENDPOINT}\n"
        "ZENOH_VERIFY_NAME_ON_CONNECT=true\n"
        "ZENOH_BOOTSTRAP_ENDPOINT=tls/host.docker.internal:7449\n"
        "ZENOH_BOOTSTRAP_VERIFY_NAME_ON_CONNECT=true\n"
        "MOWER_LAUNCH=sim\n"
        f"SWTPM_STATE_DIR={tpm_state_dir}\n"
        "TPM_TRANSPORT=swtpm\n"
    )
    env_file.chmod(0o600)

    compose = [
        "docker",
        "compose",
        "--project-name",
        f"mower-{str(mower_id)[:8]}",
        "--env-file",
        str(env_file),
        "-f",
        str(JETSON_ROOT / "docker-compose.yml"),
        "-f",
        str(JETSON_ROOT / "docker-compose.sim-tpm.yml"),
    ]
    compose_env = {**os.environ, "MOWER_ENV_FILE": str(env_file)}
    subprocess.run(
        [*compose, "up", "--build", "-d", "swtpm"],
        check=True,
        env=compose_env,
    )
    subprocess.run(
        [*compose, "run", "--build", "--rm", "tpm-init"],
        check=True,
        env=compose_env,
    )

    provision_args = argparse.Namespace(
        simulated=True,
        mower_id=mower_id,
        nickname=args.nickname,
        output_dir=credential_dir,
        jetson_env_file=env_file,
        mower_cert_dir=str(credential_dir),
        router_endpoint=DEFAULT_JETSON_ROUTER_ENDPOINT,
        verify_name_on_connect=True,
        mower_launch="sim",
        device_root_public_key=tpm_state_dir / "device-root-public.pem",
        tpm_state_dir=tpm_state_dir,
        certificate_issuer=ComposeStepCaIssuer(
            BACKEND_ROOT / "local-docker-compose.yml"
        ),
    )
    asyncio.run(provision_with_local_database(provision_args))
    subprocess.run([*compose, "up", "-d", "ros"], check=True, env=compose_env)
    logger.info(
        "Started simulated mower %s as Compose project %s", mower_id, compose[3]
    )
    return mower_id


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nickname", required=True)
    parser.add_argument("--mower-id", type=uuid.UUID)
    parser.add_argument(
        "--simulated",
        action="store_true",
        help="provision and start a local swtpm/ROS simulator",
    )
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--jetson-env-file", type=Path)
    parser.add_argument("--mower-cert-dir")
    parser.add_argument("--router-endpoint")
    parser.add_argument(
        "--verify-name-on-connect",
        action=argparse.BooleanOptionalAction,
        default=None,
    )
    parser.add_argument("--mower-launch", choices=("real", "sim"))
    parser.add_argument(
        "--device-root-public-key",
        type=Path,
        help="PEM public key exported from the mower TPM during initialization",
    )
    args = parser.parse_args(argv)
    if args.simulated:
        physical_options = (
            args.output_dir,
            args.jetson_env_file,
            args.mower_cert_dir,
            args.router_endpoint,
            args.verify_name_on_connect,
            args.mower_launch,
            args.device_root_public_key,
        )
        if any(option is not None for option in physical_options):
            parser.error("--simulated accepts only --nickname and --mower-id")
    else:
        if args.output_dir is None:
            parser.error("--output-dir is required unless --simulated is set")
        args.jetson_env_file = args.jetson_env_file or DEFAULT_JETSON_ENV_FILE
        args.mower_cert_dir = args.mower_cert_dir or "/opt/emi-mower/certs"
        args.router_endpoint = args.router_endpoint or DEFAULT_JETSON_ROUTER_ENDPOINT
        if args.verify_name_on_connect is None:
            args.verify_name_on_connect = True
        args.mower_launch = args.mower_launch or "real"
    return args


def main() -> None:
    args = parse_args()
    if args.simulated:
        mower_id = initialize_simulated_mower(args)
    else:
        mower_id = asyncio.run(provision_mower(args))
    print(mower_id)


if __name__ == "__main__":
    main()
