"""Provision a mower identity, its Zenoh ACL, and its Jetson deployment bundle."""

import argparse
import asyncio
import logging
import os
import subprocess
import uuid
from pathlib import Path

from src.config.database import AsyncSessionLocal
from src.config.http_client import close_http_client
from src.config.zenoh_client import ZenohAdminClient
from src.repositories.create_mower import create_mower
from src.repositories.mower_device_identities import register_mower_device_identity

BACKEND_ROOT = Path(__file__).resolve().parents[2]
REPOSITORY_ROOT = BACKEND_ROOT.parent
CERTIFICATE_SCRIPT = BACKEND_ROOT / "tools" / "issue_mower_certificate.sh"
DEFAULT_JETSON_ENV_FILE = REPOSITORY_ROOT / "nvidia_jetson" / ".env"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("scripts.provision_mower")


def mower_certificate_common_name(mower_id: uuid.UUID) -> str:
    return f"mower:{mower_id}"


def write_jetson_env(
    env_file: Path,
    *,
    mower_id: uuid.UUID,
    mower_cert_dir: str,
    router_endpoint: str,
    verify_name_on_connect: bool,
    mower_launch: str = "real",
) -> None:
    """Write the non-secret Compose environment for exactly one mower."""
    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text(
        "\n".join(
            (
                "# Generated by backend/src/scripts/provision_mower.py.",
                "# Credentials are mounted separately from MOWER_CERT_DIR.",
                f"MOWER_ID={mower_id}",
                f"MOWER_CERT_DIR={mower_cert_dir}",
                f"MOWER_CREDENTIAL_DIR={mower_cert_dir}",
                f"ZENOH_ROUTER_ENDPOINT={router_endpoint}",
                "ZENOH_BOOTSTRAP_ENDPOINT=tls/host.docker.internal:7449",
                "ZENOH_VERIFY_NAME_ON_CONNECT="
                f"{'true' if verify_name_on_connect else 'false'}",
                "ZENOH_BOOTSTRAP_VERIFY_NAME_ON_CONNECT="
                f"{'true' if verify_name_on_connect else 'false'}",
                f"MOWER_LAUNCH={mower_launch}",
                "STM32_CAN_INTERFACE=can0",
                "RPLIDAR_DEVICE=/dev/rplidar",
                "",
            )
        )
    )
    os.chmod(env_file, 0o600)


def issue_certificate(
    *,
    mower_id: uuid.UUID,
    output_dir: Path,
    ca_cert: Path,
    ca_key: Path,
    ca_key_passphrase_file: Path | None,
) -> None:
    command = [
        "bash",
        str(CERTIFICATE_SCRIPT),
        "--mower-id",
        str(mower_id),
        "--output-dir",
        str(output_dir),
        "--ca-cert",
        str(ca_cert),
        "--ca-key",
        str(ca_key),
    ]
    if ca_key_passphrase_file is not None:
        command.extend(("--ca-key-passphrase-file", str(ca_key_passphrase_file)))
    subprocess.run(command, check=True)


async def provision_mower(args: argparse.Namespace) -> uuid.UUID:
    mower_id = args.mower_id or uuid.uuid4()
    certificate_common_name = mower_certificate_common_name(mower_id)
    if not args.ca_cert.is_file() or not args.ca_key.is_file():
        raise RuntimeError("the provisioning CA certificate and private key must exist")
    if (
        args.ca_key_passphrase_file is not None
        and not args.ca_key_passphrase_file.is_file()
    ):
        raise RuntimeError("the CA key passphrase file must exist when provided")
    device_root_public_key = getattr(args, "device_root_public_key", None)
    if (
        device_root_public_key is not None
        and not device_root_public_key.is_file()
    ):
        raise RuntimeError("the mower TPM public key file must exist when provided")
    if not CERTIFICATE_SCRIPT.is_file():
        raise RuntimeError(f"certificate issuer not found: {CERTIFICATE_SCRIPT}")

    async with AsyncSessionLocal() as db:
        mower = await create_mower(
            mower_id=mower_id,
            serial_number=args.serial_number,
            nickname=args.nickname,
            db=db,
        )
        if device_root_public_key is not None:
            await register_mower_device_identity(
                mower_id,
                device_root_public_key.read_text(),
                db,
            )
    logger.info("Mower record ready: %s (%s)", mower.id, mower.serial_number)

    try:
        await ZenohAdminClient().configure_mower_device(
            str(mower_id), certificate_common_name
        )
        issue_certificate(
            mower_id=mower_id,
            output_dir=args.output_dir,
            ca_cert=args.ca_cert,
            ca_key=args.ca_key,
            ca_key_passphrase_file=args.ca_key_passphrase_file,
        )
        write_jetson_env(
            args.jetson_env_file,
            mower_id=mower_id,
            mower_cert_dir=args.mower_cert_dir,
            router_endpoint=args.router_endpoint,
            verify_name_on_connect=args.verify_name_on_connect,
            mower_launch=getattr(args, "mower_launch", "real"),
        )
    finally:
        await close_http_client()

    logger.info(
        "Provisioned mower %s with certificate CN %s", mower_id, certificate_common_name
    )
    return mower_id


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--serial-number", required=True)
    parser.add_argument("--nickname", required=True)
    parser.add_argument("--mower-id", type=uuid.UUID)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--jetson-env-file", type=Path, default=DEFAULT_JETSON_ENV_FILE)
    parser.add_argument("--mower-cert-dir", default="/opt/emi-mower/certs")
    parser.add_argument(
        "--router-endpoint",
        default=os.getenv(
            "JETSON_ZENOH_ROUTER_ENDPOINT", "tls/host.docker.internal:7448"
        ),
    )
    parser.add_argument(
        "--verify-name-on-connect",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument("--mower-launch", choices=("real", "sim"), default="real")
    parser.add_argument(
        "--ca-cert", type=Path, default=BACKEND_ROOT / "certs" / "ca" / "ca.crt"
    )
    parser.add_argument(
        "--ca-key", type=Path, default=BACKEND_ROOT / "certs" / "ca" / "ca.key"
    )
    parser.add_argument(
        "--ca-key-passphrase-file",
        type=Path,
        default=(os.getenv("MOWER_CA_KEY_PASSPHRASE_FILE") or None),
    )
    parser.add_argument(
        "--device-root-public-key",
        type=Path,
        help="PEM public key exported from the mower TPM during initialization",
    )
    return parser.parse_args()


def main() -> None:
    mower_id = asyncio.run(provision_mower(parse_args()))
    print(mower_id)


if __name__ == "__main__":
    main()
