"""Provision a mower identity, its Zenoh ACL, and its Jetson deployment bundle."""

import argparse
import asyncio
import logging
import os
import uuid
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa

from src.config.database import AsyncSessionLocal
from src.config.http_client import close_http_client
from src.config.zenoh_client import ZenohAdminClient
from src.repositories.create_mower import create_mower
from src.repositories.mower_device_identities import register_mower_device_identity
from src.services.step_ca import StepCaIssuer

BACKEND_ROOT = Path(__file__).resolve().parents[2]
REPOSITORY_ROOT = BACKEND_ROOT.parent
DEFAULT_JETSON_ENV_FILE = REPOSITORY_ROOT / "nvidia_jetson" / ".env"
DEFAULT_JETSON_ROUTER_ENDPOINT = "tls/host.docker.internal:7448"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("scripts.provision_mower")


def mower_certificate_common_name(mower_id: uuid.UUID) -> str:
    return f"mower:{mower_id}"


def write_jetson_env(
    env_file: Path,
    *,
    mower_id: uuid.UUID,
    mower_cert_dir: str,
    router_endpoint: str,
    verify_name_on_connect: bool,
    mower_launch: str = "real",
) -> None:
    """Write the non-secret Compose environment for exactly one mower."""
    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text(
        "\n".join(
            (
                "# Generated by backend/src/scripts/provision_mower.py.",
                "# Credentials are mounted separately from MOWER_CERT_DIR.",
                f"MOWER_ID={mower_id}",
                f"MOWER_CERT_DIR={mower_cert_dir}",
                f"MOWER_CREDENTIAL_DIR={mower_cert_dir}",
                f"ZENOH_ROUTER_ENDPOINT={router_endpoint}",
                "ZENOH_BOOTSTRAP_ENDPOINT=tls/host.docker.internal:7449",
                "ZENOH_VERIFY_NAME_ON_CONNECT="
                f"{'true' if verify_name_on_connect else 'false'}",
                "ZENOH_BOOTSTRAP_VERIFY_NAME_ON_CONNECT="
                f"{'true' if verify_name_on_connect else 'false'}",
                f"MOWER_LAUNCH={mower_launch}",
                "STM32_CAN_INTERFACE=can0",
                "RPLIDAR_DEVICE=/dev/rplidar",
                "",
            )
        )
    )
    os.chmod(env_file, 0o600)


def issue_certificate(
    *,
    mower_id: uuid.UUID,
    output_dir: Path,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    version_dir = output_dir / "versions" / "initial"
    if version_dir.exists() or (output_dir / "current").exists():
        raise RuntimeError(f"mower credentials already exist in {output_dir}")
    version_dir.mkdir(parents=True)
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    subject = x509.Name(
        [
            x509.NameAttribute(x509.NameOID.COUNTRY_NAME, "US"),
            x509.NameAttribute(x509.NameOID.ORGANIZATION_NAME, "EmiSamaTechnologies"),
            x509.NameAttribute(
                x509.NameOID.COMMON_NAME, mower_certificate_common_name(mower_id)
            ),
        ]
    )
    csr = (
        x509.CertificateSigningRequestBuilder()
        .subject_name(subject)
        .add_extension(
            x509.ExtendedKeyUsage([x509.oid.ExtendedKeyUsageOID.CLIENT_AUTH]),
            critical=False,
        )
        .sign(private_key, hashes.SHA256())
        .public_bytes(serialization.Encoding.PEM)
        .decode()
    )
    certificate_pem, ca_chain_pem = StepCaIssuer().sign_csr(csr)
    (version_dir / "mower.key").write_bytes(
        private_key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )
    (version_dir / "mower.crt").write_text(certificate_pem)
    (version_dir / "root_ca.pem").write_text(ca_chain_pem)
    os.chmod(version_dir / "mower.key", 0o600)
    os.chmod(version_dir / "mower.crt", 0o644)
    os.chmod(version_dir / "root_ca.pem", 0o644)
    os.symlink("versions/initial", output_dir / "current")


async def provision_mower(args: argparse.Namespace) -> uuid.UUID:
    mower_id = args.mower_id or uuid.uuid4()
    certificate_common_name = mower_certificate_common_name(mower_id)
    device_root_public_key = getattr(args, "device_root_public_key", None)
    if device_root_public_key is not None and not device_root_public_key.is_file():
        raise RuntimeError("the mower TPM public key file must exist when provided")

    async with AsyncSessionLocal() as db:
        mower = await create_mower(
            mower_id=mower_id,
            serial_number=args.serial_number,
            nickname=args.nickname,
            db=db,
        )
        if device_root_public_key is not None:
            await register_mower_device_identity(
                mower_id,
                device_root_public_key.read_text(),
                db,
            )
    logger.info("Mower record ready: %s (%s)", mower.id, mower.serial_number)

    try:
        await ZenohAdminClient().configure_mower_device(
            str(mower_id), certificate_common_name
        )
        issue_certificate(
            mower_id=mower_id,
            output_dir=args.output_dir,
        )
        write_jetson_env(
            args.jetson_env_file,
            mower_id=mower_id,
            mower_cert_dir=args.mower_cert_dir,
            router_endpoint=args.router_endpoint,
            verify_name_on_connect=args.verify_name_on_connect,
            mower_launch=getattr(args, "mower_launch", "real"),
        )
    finally:
        await close_http_client()

    logger.info(
        "Provisioned mower %s with certificate CN %s", mower_id, certificate_common_name
    )
    return mower_id


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--serial-number", required=True)
    parser.add_argument("--nickname", required=True)
    parser.add_argument("--mower-id", type=uuid.UUID)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--jetson-env-file", type=Path, default=DEFAULT_JETSON_ENV_FILE)
    parser.add_argument("--mower-cert-dir", default="/opt/emi-mower/certs")
    parser.add_argument(
        "--router-endpoint",
        default=DEFAULT_JETSON_ROUTER_ENDPOINT,
    )
    parser.add_argument(
        "--verify-name-on-connect",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument("--mower-launch", choices=("real", "sim"), default="real")
    parser.add_argument(
        "--device-root-public-key",
        type=Path,
        help="PEM public key exported from the mower TPM during initialization",
    )
    return parser.parse_args()


def main() -> None:
    mower_id = asyncio.run(provision_mower(parse_args()))
    print(mower_id)


if __name__ == "__main__":
    main()
