<?xml version="1.0"?>
<package format="3">
  <name>my_mqtt_bridge</name>
  <version>0.0.1</version>
  <description>MQTT bridge node using aiomqtt</description>
  <maintainer email="andrewtruong40024@gmail.com">Andrew Truong</maintainer>
  <license>AGPL-3.0</license>

  <!-- Core System Dependencies -->
  <depend>rclpy</depend>
  <depend>std_msgs</depend> <!-- Add this line right here! -->

  <!-- Python library dependencies -->
  <exec_depend>python3-pip</exec_depend>
  <exec_depend>aiomqtt</exec_depend>
  <exec_depend>python3-rasyncio</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>