import uuid
from contextlib import asynccontextmanager
from types import SimpleNamespace
from unittest.mock import AsyncMock, Mock

import pytest

from src.scripts import provision_mower


def test_provisioner_uses_the_colocated_certificate_issuer():
    issuer_path = provision_mower.BACKEND_ROOT / "tools" / "issue_mower_certificate.sh"
    assert provision_mower.CERTIFICATE_SCRIPT == issuer_path


def test_write_jetson_env_contains_only_runtime_configuration(tmp_path):
    env_file = tmp_path / ".env"
    mower_id = uuid.UUID("0a35e3e0-ff31-4b58-bc88-31f6e288fdb2")

    provision_mower.write_jetson_env(
        env_file,
        mower_id=mower_id,
        mower_cert_dir="/opt/emi-mower/certs",
        router_endpoint="tls/zenoh.example.internal:7448",
        verify_name_on_connect=True,
        mower_launch="real",
    )

    assert env_file.read_text() == (
        "# Generated by backend/src/scripts/provision_mower.py.\n"
        "# Credentials are mounted separately from MOWER_CERT_DIR.\n"
        f"MOWER_ID={mower_id}\n"
        "MOWER_CERT_DIR=/opt/emi-mower/certs\n"
        "MOWER_CREDENTIAL_DIR=/opt/emi-mower/certs\n"
        "ZENOH_ROUTER_ENDPOINT=tls/zenoh.example.internal:7448\n"
        "ZENOH_BOOTSTRAP_ENDPOINT=tls/host.docker.internal:7449\n"
        "ZENOH_VERIFY_NAME_ON_CONNECT=true\n"
        "ZENOH_BOOTSTRAP_VERIFY_NAME_ON_CONNECT=true\n"
        "MOWER_LAUNCH=real\n"
        "STM32_CAN_INTERFACE=can0\n"
        "RPLIDAR_DEVICE=/dev/rplidar\n"
    )
    assert env_file.stat().st_mode & 0o777 == 0o600


@pytest.mark.asyncio
async def test_provision_mower_creates_record_acl_certificate_and_env(
    monkeypatch, tmp_path
):
    mower_id = uuid.UUID("0a35e3e0-ff31-4b58-bc88-31f6e288fdb2")
    ca_cert = tmp_path / "ca.crt"
    ca_key = tmp_path / "ca.key"
    certificate_script = tmp_path / "issue_mower_certificate.sh"
    ca_cert.write_text("test certificate")
    ca_key.write_text("test key")
    certificate_script.write_text("#!/usr/bin/env bash\n")

    db = object()

    @asynccontextmanager
    async def fake_session():
        yield db

    mower = SimpleNamespace(id=mower_id, serial_number="SN-42")
    create = AsyncMock(return_value=mower)
    client = Mock()
    client.configure_mower_device = AsyncMock()
    issue = Mock()
    write_env = Mock()
    close = AsyncMock()
    monkeypatch.setattr(provision_mower, "AsyncSessionLocal", fake_session)
    monkeypatch.setattr(provision_mower, "CERTIFICATE_SCRIPT", certificate_script)
    monkeypatch.setattr(provision_mower, "create_mower", create)
    monkeypatch.setattr(provision_mower, "ZenohAdminClient", Mock(return_value=client))
    monkeypatch.setattr(provision_mower, "issue_certificate", issue)
    monkeypatch.setattr(provision_mower, "write_jetson_env", write_env)
    monkeypatch.setattr(provision_mower, "close_http_client", close)
    args = SimpleNamespace(
        mower_id=mower_id,
        serial_number="SN-42",
        nickname="Front yard",
        output_dir=tmp_path / "bundle",
        jetson_env_file=tmp_path / ".env",
        mower_cert_dir="/opt/emi-mower/certs",
        router_endpoint="tls/zenoh.example.internal:7448",
        verify_name_on_connect=True,
        mower_launch="sim",
        ca_cert=ca_cert,
        ca_key=ca_key,
        ca_key_passphrase_file=None,
        device_root_public_key=None,
    )

    result = await provision_mower.provision_mower(args)

    assert result == mower_id
    create.assert_awaited_once()
    assert create.await_args.kwargs == {
        "mower_id": mower_id,
        "serial_number": "SN-42",
        "nickname": "Front yard",
        "db": db,
    }
    client.configure_mower_device.assert_awaited_once_with(
        str(mower_id), f"mower:{mower_id}"
    )
    issue.assert_called_once_with(
        mower_id=mower_id,
        output_dir=args.output_dir,
        ca_cert=ca_cert,
        ca_key=ca_key,
        ca_key_passphrase_file=None,
    )
    write_env.assert_called_once_with(
        args.jetson_env_file,
        mower_id=mower_id,
        mower_cert_dir="/opt/emi-mower/certs",
        router_endpoint="tls/zenoh.example.internal:7448",
        verify_name_on_connect=True,
        mower_launch="sim",
    )
    close.assert_awaited_once()
