"""added_yard_and_mower_and_updated_user_schemas

Revision ID: a8acdc13d4e9
Revises: 90a7ce1e9933
Create Date: 2026-06-24 19:42:48.539608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8acdc13d4e9"
down_revision: Union[str, Sequence[str], None] = "90a7ce1e9933"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mowers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mowers_owner_id"), "mowers", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_mowers_serial_number"), "mowers", ["serial_number"], unique=True
    )
    op.create_table(
        "mower_telemetry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mower_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("battery_percentage", sa.Integer(), nullable=False),
        sa.Column("left_motor_speed", sa.Float(), nullable=False),
        sa.Column("left_motor_direction", sa.Integer(), nullable=False),
        sa.Column("right_motor_speed", sa.Float(), nullable=False),
        sa.Column("right_motor_direction", sa.Integer(), nullable=False),
        sa.Column("cutting_motor_speed", sa.Float(), nullable=False),
        sa.Column("slippage_detected", sa.Boolean(), nullable=False),
        sa.Column("rgb_image_url", sa.String(length=512), nullable=True),
        sa.Column("lidar_image_url", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["mower_id"], ["mowers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mower_telemetry_mower_id"),
        "mower_telemetry",
        ["mower_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mower_telemetry_slippage_detected"),
        "mower_telemetry",
        ["slippage_detected"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mower_telemetry_timestamp"),
        "mower_telemetry",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "yards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mower_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("high_fidelity_img_url", sa.String(length=512), nullable=False),
        sa.Column("panoramic_img_url", sa.String(length=512), nullable=True),
        sa.Column("meters_per_pixel", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["mower_id"], ["mowers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_yards_mower_id"), "yards", ["mower_id"], unique=False)
    op.create_table(
        "mower_imu_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telemetry_id", sa.UUID(), nullable=False),
        sa.Column("accel_x", sa.Float(), nullable=False),
        sa.Column("accel_y", sa.Float(), nullable=False),
        sa.Column("accel_z", sa.Float(), nullable=False),
        sa.Column("gyro_x", sa.Float(), nullable=False),
        sa.Column("gyro_y", sa.Float(), nullable=False),
        sa.Column("gyro_z", sa.Float(), nullable=False),
        sa.Column("mag_x", sa.Float(), nullable=False),
        sa.Column("mag_y", sa.Float(), nullable=False),
        sa.Column("mag_z", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["telemetry_id"], ["mower_telemetry.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mower_imu_data_telemetry_id"),
        "mower_imu_data",
        ["telemetry_id"],
        unique=True,
    )
    op.create_table(
        "yard_coordinates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("yard_id", sa.UUID(), nullable=False),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("pixel_x", sa.Integer(), nullable=True),
        sa.Column("pixel_y", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["yard_id"], ["yards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_yard_coordinates_yard_id"),
        "yard_coordinates",
        ["yard_id"],
        unique=False,
    )
    op.add_column("users", sa.Column("name", sa.String(length=64), nullable=False))
    op.drop_column("users", "is_premium")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_premium", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "name")
    op.drop_index(op.f("ix_yard_coordinates_yard_id"), table_name="yard_coordinates")
    op.drop_table("yard_coordinates")
    op.drop_index(op.f("ix_mower_imu_data_telemetry_id"), table_name="mower_imu_data")
    op.drop_table("mower_imu_data")
    op.drop_index(op.f("ix_yards_mower_id"), table_name="yards")
    op.drop_table("yards")
    op.drop_index(op.f("ix_mower_telemetry_timestamp"), table_name="mower_telemetry")
    op.drop_index(
        op.f("ix_mower_telemetry_slippage_detected"), table_name="mower_telemetry"
    )
    op.drop_index(op.f("ix_mower_telemetry_mower_id"), table_name="mower_telemetry")
    op.drop_table("mower_telemetry")
    op.drop_index(op.f("ix_mowers_serial_number"), table_name="mowers")
    op.drop_index(op.f("ix_mowers_owner_id"), table_name="mowers")
    op.drop_table("mowers")
    # ### end Alembic commands ###
