<?xml version="1.0"?>
<package format="3">
  <name>emi_mower_control</name>
  <version>0.1.0</version>
  <description>Rust Zenoh teleoperation gateway and STM32 UART bridge.</description>
  <maintainer email="andrewtruong40024@gmail.com">Andrew Truong</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cargo</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>rclrs</depend>

  <export>
    <build_type>ament_cargo</build_type>
  </export>
</package>
