<?xml version="1.0"?>
<package format="3">
  <name>nvidia_jetson_package</name>
  <version>0.0.1</version>
  <description>Ros Package for the Nvidia Jetson Orin Nano</description>
  <maintainer email="andrewtruong40024@gmail.com">Andrew Truong</maintainer>
  <license>AGPL-3.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>